// Modals
export const SHOW_AUTH_MODAL = 'SHOW_AUTH_MODAL';
export const HIDE_AUTH_MODAL = 'HIDE_AUTH_MODAL';

// Notes
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const RETREIVE_NOTE_SUCCESS = 'RETREIVE_NOTE_SUCCESS';
